product As screen:
    OnVisible: |
        =If(Or(CountRows(OfflineBookingData)>0,CountRows(OfflineTimeEntry)>0,CountRows(OfflinePictureSignature)>0,CountRows(OfflineAccount)>0,CountRows(OfflineContact)>0),
        If( Connection.Connected,
            ForAll(OfflineBookingData, Patch('Bookable Resource Bookings',ThisRecord.BookingItem,{Name: ThisRecord.Name, 'Start Time':ThisRecord.'Start Time','End Time':ThisRecord.'End Time','Actual Arrival Time':ThisRecord.'Actual Arrival Time','Estimated Arrival Time':ThisRecord.'Estimated Arrival Time',Duration:ThisRecord.Duration,'Booking Status':ThisRecord.'Booking Status', 'Booking Type': ThisRecord.'Booking Type', Resource:ThisRecord.Resource}));
            Clear(OfflineBookingData); Refresh('Bookable Resource Bookings'); ForAll(OfflineTimeEntry, Patch('Time Entries',ThisRecord.TimeEntryItem,{'Bookable Resource':ThisRecord.'Bookable Resource',Type:ThisRecord.Type, Start:ThisRecord.Start, End:ThisRecord.End, Date:ThisRecord.Date, 'Work Order':ThisRecord.'Work Order', 'Bookable Resource Booking':ThisRecord.'Bookable Resource Booking', 'Entry Status':ThisRecord.'Entry Status', Description: ThisRecord.Description, 'External Comments':ThisRecord.'External Comments'}));
            Clear(OfflineTimeEntry); Refresh('Time Entries');
            ForAll(OfflineAccount,Patch(Accounts, ThisRecord.AccountItem, {'Account Name':ThisRecord.'Account Name', 'Main Phone':ThisRecord.'Main Phone', Email:ThisRecord.Email, 'Address 1: City':ThisRecord.'Address 1: City'}));
            Clear(OfflineAccount); Refresh(Accounts);
        ForAll(OfflineContact,Patch(Contacts, ThisRecord.ContactItem, {'First Name':ThisRecord.'First Name', 'Last Name':ThisRecord.'Last Name', Email:ThisRecord.Email, 'Business Phone':ThisRecord.'Business Phone'}));
            Clear(OfflineContact); Refresh(Contacts);
            ForAll(OfflinePictureSignature,Patch(Notes,Defaults(Notes),{'File Name':ThisRecord.'File Name',Title:ThisRecord.Title,Regarding:ThisRecord.Regarding, Document:ThisRecord.Document, 'Is Document':ThisRecord.'Is Document'}));
            Clear(OfflinePictureSignature);Notify("Data is Updated Online Successfully",NotificationType.Success)
        );)

    "Gallery11 As gallery.'BrowseLayout_Vertical_ThreeTextVariant_ver4.0'":
        Height: =1001
        Items: =Products
        Layout: =Layout.Vertical
        TemplatePadding: =0
        TemplateSize: =250
        Y: =135
        ZIndex: =1

        Title11 As label:
            Height: =36
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =7
            ZIndex: =1

        Subtitle7 As label:
            Height: =35
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Product ID'
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =56
            ZIndex: =2

        Body4 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Product Type'
            VerticalAlign: =VerticalAlign.Top
            Width: =255
            X: =238
            Y: =108
            ZIndex: =3

        Separator21 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =5

        Label22 As label:
            FontWeight: =FontWeight.Bold
            Height: =36
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Name:"
            Width: =560
            Y: =10
            ZIndex: =6

        Label22_1 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Product ID:"
            Width: =238
            Y: =53
            ZIndex: =7

        Label22_2 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Product Type:"
            Width: =238
            Y: =98
            ZIndex: =8

        Label22_3 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Default Unit:"
            Width: =200
            Y: =149
            ZIndex: =9

        Body4_1 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Default Unit'.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =159
            ZIndex: =10

        Body4_2 As label:
            Height: =41
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Default Price List'.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =402
            X: =238
            Y: =209
            ZIndex: =11

        Label22_4 As label:
            FontWeight: =FontWeight.Bold
            Height: =41
            OnSelect: =Select(Parent)
            Size: =21
            Text: |-
                ="Price List:"
            Width: =200
            Y: =199
            ZIndex: =12

        Arrow1 As arrow:
            Height: =46
            OnSelect: =Select(Parent);Navigate('Product view');
            Width: =52
            X: =560
            Y: =104
            ZIndex: =13

    Component1_16 As Component1:
        Height: =70
        ZIndex: =2

    Label7_3 As label:
        Align: =Align.Center
        Fill: =RGBA(209, 232, 178, 1)
        Height: =70
        Size: =21
        Text: ="Products"
        Width: =640
        Y: =65
        ZIndex: =3

    MenuLeftNav_9 As MenuLeftNav:
        ExpandMenu: =true
        Height: =MenuLeftNav_9.MenuHeight
        Visible: =true
        Width: =MenuLeftNav_9.MenuWidth
        ZIndex: =5

    Timer1_17 As timer:
        AutoStart: =true
        Duration: =10000
        Height: =66
        OnTimerEnd: |
            =If(Or(CountRows(OfflineBookingData)>0,CountRows(OfflineTimeEntry)>0,CountRows(OfflinePictureSignature)>0,CountRows(OfflineAccount)>0,CountRows(OfflineContact)>0),
            If( Connection.Connected,
                ForAll(OfflineBookingData, Patch('Bookable Resource Bookings',ThisRecord.BookingItem,{Name: ThisRecord.Name, 'Start Time':ThisRecord.'Start Time','End Time':ThisRecord.'End Time','Actual Arrival Time':ThisRecord.'Actual Arrival Time','Estimated Arrival Time':ThisRecord.'Estimated Arrival Time',Duration:ThisRecord.Duration,'Booking Status':ThisRecord.'Booking Status', 'Booking Type': ThisRecord.'Booking Type', Resource:ThisRecord.Resource}));
                Clear(OfflineBookingData); Refresh('Bookable Resource Bookings'); ForAll(OfflineTimeEntry, Patch('Time Entries',ThisRecord.TimeEntryItem,{'Bookable Resource':ThisRecord.'Bookable Resource',Type:ThisRecord.Type, Start:ThisRecord.Start, End:ThisRecord.End, Date:ThisRecord.Date, 'Work Order':ThisRecord.'Work Order', 'Bookable Resource Booking':ThisRecord.'Bookable Resource Booking', 'Entry Status':ThisRecord.'Entry Status', Description: ThisRecord.Description, 'External Comments':ThisRecord.'External Comments'}));
                Clear(OfflineTimeEntry); Refresh('Time Entries');
                ForAll(OfflineAccount,Patch(Accounts, ThisRecord.AccountItem, {'Account Name':ThisRecord.'Account Name', 'Main Phone':ThisRecord.'Main Phone', Email:ThisRecord.Email, 'Address 1: City':ThisRecord.'Address 1: City'}));
                Clear(OfflineAccount); Refresh(Accounts);
            ForAll(OfflineContact,Patch(Contacts, ThisRecord.ContactItem, {'First Name':ThisRecord.'First Name', 'Last Name':ThisRecord.'Last Name', Email:ThisRecord.Email, 'Business Phone':ThisRecord.'Business Phone'}));
                Clear(OfflineContact); Refresh(Contacts);
                ForAll(OfflinePictureSignature,Patch(Notes,Defaults(Notes),{'File Name':ThisRecord.'File Name',Title:ThisRecord.Title,Regarding:ThisRecord.Regarding, Document:ThisRecord.Document, 'Is Document':ThisRecord.'Is Document'}));
                Clear(OfflinePictureSignature);Notify("Data is Updated Online Successfully",NotificationType.Success)
            );)
        Repeat: =true
        Visible: =false
        Width: =202
        X: =20
        Y: =92
        ZIndex: =6

